language: node_js
node_js:
  - "node"
os: osx
osx_image: xcode9.2

before_install:
  - sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok

install:
  - npm install -g --save-dev nightwatch

script:
  - nightwatch --config nightwatch.json