language: node_js
node_js:
  - "node"
os: osx
osx_image: xcode9.2

addons:
  chrome: beta

before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --disable-gpu --remote-debugging-port=9222 http://localhost &"

install:
  - npm install -g --save-dev nightwatch

script:
  - nightwatch --config nightwatch.json